#
# Makefile for the 8250 serial device drivers.
#

#obj-y		+= 8250.o 8250_base.o
#8250-y					:= 8250_core.o
#8250-y		+= 8250_pnp.o
#8250_base-y				:= 8250_port.o
#8250_base-y	+= 8250_dma.o
#obj-y		+= 8250_gsc.o
obj-m		+= 8250_pci.o
#obj-y		+= 8250_hp300.o
#obj-y		+= serial_cs.o
#obj-y		+= 8250_acorn.o
#obj-y	+= 8250_early.o
#obj-y	+= 8250_fourport.o
#obj-y	+= 8250_accent.o
#obj-y		+= 8250_boca.o
#obj-y	+= 8250_exar_st16c554.o
#obj-y		+= 8250_hub6.o
#obj-y		+= 8250_fsl.o
#obj-y		+= 8250_dw.o
#obj-y		+= 8250_em.o
#obj-y		+= 8250_omap.o
#obj-y	+= 8250_fintek.o
#obj-y	+= 8250_lpc18xx.o
#obj-y	+= 8250_mtk.o
#obj-y	+= 8250_uniphier.o
#obj-y	+= 8250_ingenic.o
#obj-y		+= 8250_mid.o

#CFLAGS_8250_ingenic.o += -I$(srctree)/scripts/dtc/libfdt
